### ISSUE TITLE
i'm not exactly sure what's wrong here

### ISSUE THREAD

**Issue by 0xFireball** [marcosmoura/vue-material#223]
This is my error:
It worked fine in previous versions, my component is just a toolbar with a simple sidenav.
I have updated my code to work with the new theming in `0.5.x`.
```
(unknown) [Vue warn]: Error when rendering component <md-sidenav>: 
warn
(unknown) TypeError: e is not a function
    at Proxy.render (eval at <anonymous> (app.js:1246), <anonymous>:9:19971)
    at VueComponent.Vue._render (eval at <anonymous> (app.js:610), <anonymous>:2252:22)
    at VueComponent.eval (eval at <anonymous> (app.js:610), <anonymous>:1699:21)
    at Watcher.get (eval at <anonymous> (app.js:610), <anonymous>:740:27)
    at new Watcher (eval at <anonymous> (app.js:610), <anonymous>:732:12)
    at VueComponent.Vue._mount (eval at <anonymous> (app.js:610), <anonymous>:1698:19)
    at VueComponent.Vue$3.$mount (eval at <anonymous> (app.js:610), <anonymous>:5718:15)
    at VueComponent.Vue$3.$mount (eval at <anonymous> (app.js:610), <anonymous>:7870:16)
    at init (eval at <anonymous> (app.js:610), <anonymous>:1988:11)
    at createElm (eval at <anonymous> (app.js:610), <anonymous>:3867:56)
    at createChildren (eval at <anonymous> (app.js:610), <anonymous>:3913:40)
    at createElm (eval at <anonymous> (app.js:610), <anonymous>:3898:7)
    at VueComponent.patch [as __patch__] (eval at <anonymous> (app.js:610), <anonymous>:4246:7)
    at VueComponent.Vue._update (eval at <anonymous> (app.js:610), <anonymous>:1724:19)
    at VueComponent.eval (eval at <anonymous> (app.js:610), <anonymous>:1699:10)
    at Watcher.get (eval at <anonymous> (app.js:610), <anonymous>:740:27)
    at new Watcher (eval at <anonymous> (app.js:610), <anonymous>:732:12)
    at VueComponent.Vue._mount (eval at <anonymous> (app.js:610), <anonymous>:1698:19)
    at VueComponent.Vue$3.$mount (eval at <anonymous> (app.js:610), <anonymous>:5718:15)
    at VueComponent.Vue$3.$mount (eval at <anonymous> (app.js:610), <anonymous>:7870:16)
    at init (eval at <anonymous> (app.js:610), <anonymous>:1988:11)
    at createElm (eval at <anonymous> (app.js:610), <anonymous>:3867:56)
    at updateChildren (eval at <anonymous> (app.js:610), <anonymous>:4075:43)
    at patchVnode (eval at <anonymous> (app.js:610), <anonymous>:4137:29)
    at VueComponent.patch [as __patch__] (eval at <anonymous> (app.js:610), <anonymous>:4250:9)
    at VueComponent.Vue._update (eval at <anonymous> (app.js:610), <anonymous>:1726:19)
    at VueComponent.eval (eval at <anonymous> (app.js:610), <anonymous>:1699:10)
    at Watcher.get (eval at <anonymous> (app.js:610), <anonymous>:740:27)
    at Watcher.run (eval at <anonymous> (app.js:610), <anonymous>:809:22)
    at Array.flushSchedulerQueue (eval at <anonymous> (app.js:610), <anonymous>:627:13)
    at nextTickHandler (eval at <anonymous> (app.js:610), <anonymous>:405:16)
Vue._render
```

**Comment by 0xFireball** [comment]
Here's another stacktrace:

```
vue.js?3de6:2643 [Vue warn]: Error when rendering component <md-sidenav>: 
warn @ vue.js?3de6:2643
Vue._render @ vue.js?3de6:2255
(anonymous) @ vue.js?3de6:1699
get @ vue.js?3de6:740
run @ vue.js?3de6:809
flushSchedulerQueue @ vue.js?3de6:627
nextTickHandler @ vue.js?3de6:405
vue.js?3de6:2264 TypeError: e is not a function
    at Proxy.render (eval at <anonymous> (app.js:1246), <anonymous>:9:19971)
    at VueComponent.Vue._render (eval at <anonymous> (app.js:610), <anonymous>:2252:22)
    at VueComponent.eval (eval at <anonymous> (app.js:610), <anonymous>:1699:21)
    at Watcher.get (eval at <anonymous> (app.js:610), <anonymous>:740:27)
    at Watcher.run (eval at <anonymous> (app.js:610), <anonymous>:809:22)
    at Array.flushSchedulerQueue (eval at <anonymous> (app.js:610), <anonymous>:627:13)
    at nextTickHandler (eval at <anonymous> (app.js:610), <anonymous>:405:16)
```

**Comment by 0xFireball** [comment]
Reinstalling Vue and Vue material solved the problem. I'm not sure what was wrong, but it's fixed now!

Vue Material is the best!
