### ISSUE TITLE
some theme error

### ISSUE THREAD

**Issue by nictaylr** [marcosmoura/vue-material#220]
```
vue.js?3de6:2643 [Vue warn]: Error when rendering component <md-sidenav>: 
warn @ vue.js?3de6:2643
Vue._render @ vue.js?3de6:2255
(anonymous) @ vue.js?3de6:1699
get @ vue.js?3de6:740
run @ vue.js?3de6:809
flushSchedulerQueue @ vue.js?3de6:627
nextTickHandler @ vue.js?3de6:405
vue.js?3de6:2264 TypeError: Cannot read property 'currentTheme' of undefined
    at VueComponent.themeClass (eval at <anonymous> (app.js:1246), <anonymous>:1:986)
    at Watcher.get (eval at <anonymous> (app.js:610), <anonymous>:740:27)
    at Watcher.evaluate (eval at <anonymous> (app.js:610), <anonymous>:848:21)
    at Proxy.computedGetter (eval at <anonymous> (app.js:610), <anonymous>:1310:15)
    at Proxy.render (eval at <anonymous> (app.js:1246), <anonymous>:15:19271)
    at VueComponent.Vue._render (eval at <anonymous> (app.js:610), <anonymous>:2252:22)
    at VueComponent.eval (eval at <anonymous> (app.js:610), <anonymous>:1699:21)
    at Watcher.get (eval at <anonymous> (app.js:610), <anonymous>:740:27)
    at Watcher.run (eval at <anonymous> (app.js:610), <anonymous>:809:22)
    at Array.flushSchedulerQueue (eval at <anonymous> (app.js:610), <anonymous>:627:13)
    at nextTickHandler (eval at <anonymous> (app.js:610), <anonymous>:405:16)
```

I upgraded to v5, and updated code to use new theme API

**Comment by jtouzy** [comment]
+1 Same error when updating to v5 and updated theme API.

I think this is related to : 
``Vue.material.currentTheme``, in the ``MdTheme`` mixin : [see here](https://github.com/marcosmoura/vue-material/blob/master/src/core/components/mdTheme/mixin.js#L35)
But I don't see why Vue.material wouldn't be initialized when the App renders.

**Comment by VicarEscaped** [comment]
Hi, everyone!
which Vue version do you use? I play with Vue version on [codepen](http://codepen.io/vue-material/pen/WGavBE) and get error on 2.1.6 version:

> Uncaught TypeError: t._h is not a function
    at o.render (VM308 vue-material.js:9)
    at o.n._render (VM130 vue.min.js:6)
    at o.<anonymous> (VM130 vue.min.js:6)
    at Pi.get (VM130 vue.min.js:7)
    at new Pi (VM130 vue.min.js:7)
    at o.e._mount (VM130 vue.min.js:6)
    at o.Ie.$mount (VM130 vue.min.js:8)
    at o.Ie.$mount (VM130 vue.min.js:8)
    at fe (VM130 vue.min.js:6)
    at s (VM130 vue.min.js:6)

**Comment by odranoelBR** [comment]
Same error here !

**Comment by rslhdyt** [comment]
I had same error when migrate to 0.5.0, Vue version 2.1.0

**Comment by huhk-sysu** [comment]
same error in vue-material@0.5.0 && vue@2.1.6
![image](https://cloud.githubusercontent.com/assets/14769033/21263995/bbe219b8-c3d4-11e6-977f-19cfcc8ff574.png)
when I write like below
``` jade
<template lang="pug">
  .body-container
    router-view
</template>

and if I add a `md-theme` directive like this(By the way I have registered the default theme in `main.js`)
``` jade
<template lang="pug">
  .body-container
    md-theme(md-name='default')
      router-view
</template>
```
the error show up like this
![image](https://cloud.githubusercontent.com/assets/14769033/21264084/4450e158-c3d5-11e6-8713-dc10c1517601.png)
![image](https://cloud.githubusercontent.com/assets/14769033/21264088/48715164-c3d5-11e6-9ca1-a1295cca8de4.png)

**Comment by nicolas-bonnel** [comment]
Same as above with vue-material@0.5.0 && vue@2.1.6

**Comment by marcosmoura** [comment]
I'm checking that. I'm sorry about this!

**Comment by BRKsDeadPool** [comment]
Same error! but still render the <md-whiteframe> for some reason

**Comment by marcosmoura** [comment]
Already found the problem. Working on it!

**Comment by marcosmoura** [comment]
Fixed! Was a problem on Vue Material instance affecting only non commonjs env. To fix I had to expose the instance inside Vue instances as well. No breaking changes though:
``` javascript
this.$material.setCurrentTheme('about')
```

Sorry about this ugly bug!
